artifact_uri: file:///Users/user/Documents/Project/MLflow-and-Dagshub/mlruns_local/0/4d8e6b3b5b944a3eaadcdbf160b55bea/artifacts
end_time: 1720675411797
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4d8e6b3b5b944a3eaadcdbf160b55bea
run_name: sedate-trout-773
run_uuid: 4d8e6b3b5b944a3eaadcdbf160b55bea
source_name: ''
source_type: 4
source_version: ''
start_time: 1720675407439
status: 3
tags: []
user_id: user
