artifact_uri: file:///Users/user/Documents/Project/MLflow-and-Dagshub/mlruns_local/0/215c6c17cfbf4b938303bbbcfabee7ed/artifacts
end_time: 1720633280725
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 215c6c17cfbf4b938303bbbcfabee7ed
run_name: dapper-gnu-301
run_uuid: 215c6c17cfbf4b938303bbbcfabee7ed
source_name: ''
source_type: 4
source_version: ''
start_time: 1720633276871
status: 3
tags: []
user_id: user
